[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sol_token = "JCX3jF4us89VaEUmimya9kSmmD2magNqh7Mr7z4WCQxh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/macbookpro/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
