[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.25"

[features]
seeds = false
skip-lint = false

[programs.devnet]
sol_token = "JCX3jF4us89VaEUmimya9kSmmD2magNqh7Mr7z4WCQxh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/macbookpro/Solana/Solana_Token/sol-token/keys/main.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
